name: Patch upstream

on:
  push:
    branches:
      - patch

jobs:
  get-release-tags:
    runs-on: ubuntu-latest
    outputs:
      upstream_release: ${{ steps.upstream-release.outputs.upstream_release }}
      local_tag: ${{ steps.local-tag.outputs.local_tag }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Get latest upstream release
        id: upstream-release
        shell: bash
        run: |
          latest_release=$(gh release list --limit 1 -R linkwarden/linkwarden | awk '{ print $1 }')
          echo "upstream_release=${latest_release}" >> "$GITHUB_OUTPUT"
          echo "upstream_release=${latest_release}"

      - name: Get latest local tag
        id: local-tag
        shell: bash
        run: |
          local_tag=$(gh release list --limit 1 -R chrisbsmith/linkwarden | awk '{ print $1 }')
          echo "local_tag=${local_tag}" >> "$GITHUB_OUTPUT"
          echo "local_tag=${local_tag}"

  checkout-upstream:
    if: needs.get-release-tags.outputs.upstream_release != needs.get-release-tags.outputs.local_tag
    runs-on: ubuntu-latest
    needs:
      - get-release-tags
    env:
      ref: ${{ needs.get-release-tags.outputs.upstream_release }}
    steps:
      - name: Checkout local repo
        uses: actions/checkout@v4
        with:
          ref: patch
          path: patch

      - name: Clone upstream Linkwarden repo
        uses: actions/checkout@v4
        with:
          repository: linkwarden/linkwarden
          ref: ${{env.ref}}

      - name: Apply Patch
        shell: bash
        run: |
          find .
          git apply linkwarden.patch

